# Site settings
title: Kasper Holbek Jensen Photos
email: kholbekj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kasper Holbek Jensen's photos
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kholbekj-photo.surge.sh" # the base hostname & protocol for your site
twitter_username: kholbek
github_username:  kholbekj

# Build settings
markdown: kramdown
